src/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'homes/about'=>'homes/about', as: 'about'
  resources :post_books, only: [:new, :index, :show, :create, :destroy] do
    resources :book_comments, only: [:create,:destroy]
  end
  resources :users, only: [:show,:edit,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/book_category_relation.rb
class BookCategoryRelation < ApplicationRecord
    belongs_to :post_book
    belongs_to :category
end

src/app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :post_book
end

src/app/models/category.rb
class Category < ApplicationRecord
    has_many :book_category_relations, dependent: :destroy
    has_many :post_books, through: :book_category_relations
end

src/app/models/post_book.rb
class PostBook < ApplicationRecord
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :book_category_relations, dependent: :destroy
    has_many :categories, through: :book_category_relations

    validates :title, presence: true
    validates :body, presence: true
end

src/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  validates :email, uniqueness: true

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!, except: [:top]
    def after_sign_in_path_for(resource)
        post_books_path
    end
    def after_sign_out_path_for(resource)
        root_path
    end
    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

src/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    def create
        post_book = PostBook.find(params[:post_book_id])
        comment = BookComment.new(book_comment_params)
        comment.user_id = current_user.id
        comment.post_book_id = post_book.id
        comment.save
        redirect_to post_book_path(post_book)
    end

    def destroy
        BookComment.find(params[:id]).destroy
        redirect_to post_book_path(params[:post_book_id])
    end
    private

    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end
end

src/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

src/app/controllers/post_books_controller.rb
class PostBooksController < ApplicationController
  def new
    @post_book = PostBook.new
  end

  def create
    @post_book = PostBook.new(post_book_params)
    @post_book.user_id = current_user.id
    if @post_book.save
      redirect_to post_books_path
    else
      render :new
    end
  end

  def index
    @post_books = params[:category_id].present? ? Category.find(params[:category_id]).post_books : PostBook.all
  end

  def show
    @post_book = PostBook.find(params[:id])
    @book_comment = BookComment.new
  end

  def destroy
    @post_book = PostBook.find(params[:id])
    @post_book.delete
    redirect_to post_books_path
  end

  private

  def post_book_params
    params.require(:post_book).permit(:title, :body, category_ids: [])
  end
end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_books = @user.post_books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

src/app/helpers/homes_helper.rb
module HomesHelper
end

src/app/helpers/post_books_helper.rb
module PostBooksHelper
end

src/app/helpers/users_helper.rb
module UsersHelper
end

src/app/views/homes/about.html.erb
<h1>About<h1>

src/app/views/homes/top.html.erb
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">Welcome to Short Short</h1>
    <h2>Let's start!</h2>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">
            "100字以内で小説を書いて公開してみよう"
        </p>
    </div>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <% if user_signed_in? %>
        <button type="button" class="btn btn-primary btn-lg px-4 me-sm-3">
            <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link text-dark' %>
        </button>
        <button type="button" class="btn btn-outline-secondary btn-lg px-4">
            <%= link_to 'My Page', user_path(current_user.id), class: 'nav-link text-dark' %>
        </button>
        <% else %>
        <button type="button" class="btn btn-primary btn-lg px-4 me-sm-3">
            <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link text-dark' %>
        </button>
        <button type="button" class="btn btn-outline-secondary btn-lg px-4">
            <%= link_to "Log in", new_user_session_path, class: 'nav-link text-dark' %>
        </button>
        <% end %>
    </div>
</div>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Post', new_post_book_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'My Page', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Books', post_books_path, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pt-5 ">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>Short Short</p>
          </div>
          <div class="col-md-4">
            <h6>このアプリについて</h6>
            <ul class="menu list-unstyled">
              <li>
                <%= link_to 'Top', root_path, class: 'text-light' %>
              </li>
              <li>
                <a class="text-light text-decoration-none" href="" data-toggle="collapse" data-target="#ex-1" area-expanded="false" area-control="ex-1">作成者</a>
                <p class="collapse" id="ex-1">
                  某国立大学院生 S.K
                </p>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

src/app/views/post_books/index.html.erb
<div class="px-5 pt-5">
<%= form_tag post_books_path, method: :get, class: 'boards_serchForm'  do %>
  <% select_tag :category_id,
                options_from_collection_for_select(Category.all, :id, :name, params[:category_id]),
                {
                  prompt: 'カテゴリー検索',
                  onchange: 'submit(this.form)'
                }
  %>
<% end %>
</div>

<%# 投稿一覧　%>
<div class="card-list-container py-5 mb-5">
  <% @post_books.each do |post_book| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <div class="row">
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_book_path(post_book.id), class:"text-dark") do %>
              <strong><i class="fa-regular fa-book"></i><span> <%= post_book.title %></span></strong>
            <% end %>
          </p>
          <p class="card-text">Story：<%= post_book.body %></p>
          <span><i class="fas fa-user"></i> By <%= post_book.user.name %> ｜ </span>
          <span class="text-dark p-1">
          <% post_book.categories.each do |category| %>
            #<%= category.name %>
          <% end %>
          </span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

src/app/views/post_books/new.html.erb
<div class="error-message p-5 border">
    <% if @post_book.errors.any? %>
        <%= @post_book.errors.count %>エラー
        <% @post_book.errors.full_messages.each do |message|%>
            <p><%= message %></p>
        <% end %>
    <% end %>
</div>

<div class="p-5">
<h1>投稿フォーム</h1>
    <%= form_with model: @post_book do |f| %>
        <p><%= f.text_field :title, class:"form-control", placeholder:"Title" %></p>
        <p><%= f.text_area :body, class:"form-control", placeholder:"Story in 100 words" %></p>
        <p class="border p-2">
            <%= f.label :category, 'カテゴリ', class: "font-weight-bold pr-3" %>
            <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name, include_hidden: false) do |category| %>
                <%= category.label do %>
                    <%= category.check_box %>
                    <%= category.text %>
                <% end %>
            <% end %>
        </p>
        <div class="text-right"><%= f.submit 'Post', class:"btn btn-lg btn-primary mt-4" %></div>
    <% end %>
</div>

src/app/views/post_books/show.html.erb
<div class="card-list-container py-5">
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <div class="row">
        <div class="col-8">
          <p class="card-title">
            <strong><i class="fa-solid fa-book"></i><span> <%= @post_book.title %></span></strong>
          </p>
          <p>Date：<%= @post_book.created_at.strftime('%Y/%m/%d') %></p>
          <p class="card-text">Story：<%= @post_book.body %></p>
          <span><i class="fas fa-user"></i> By <%= @post_book.user.name %> ｜ </span>
          <% if @post_book.user == current_user %>
            <%= link_to "Delete", post_book_path(@post_book), method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container pt-2 bg-light">
  <div class="comment-title"><h2>みんなのコメント</h2></div>
  <div class="comment-field p-4 mb-3">
    <% @post_book.book_comments.each do |book_comment| %>
    <div class="comment-box d-flex bg-highlight mb-3 border">
      <div class="comment-user-name text-black p-2 border-right"><p><%= book_comment.user.name %><p></div>
      <div class="comment-body flex-grow-1 border-right text-black p-2"><p><%= book_comment.comment %></p></div>
      <% if book_comment.user == current_user %>
        <div class="comment-delete ml-auto p-2"><p class="border-bottom"><%= link_to "削除", post_book_book_comment_path(book_comment.post_book ,book_comment), method: :delete %></p></div>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

<div class="container p-3 mb-5 bg-light">
  <h2>コメントする<h2/>
  <div class="post-comment bg-white p-2">
    <%= form_with model: [@post_book, @book_comment] do |f| %>
      <div><p><%= f.text_area :comment, rows: '5', placeholder: "コメントを書く" %></p></div>
      <div><p><%= f.submit "comment" %></p></div>
    <% end %>
</div>

src/app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= form_with model: @user do |f| %>
    <label for="inputName">Name</label>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
    <label for="inputImage">ProfileImage</label>
    <%= f.file_field :profile_image, placeholder: "prifile image", accept: "image/*" %>
    <p><%= f.submit "Save" %></p>
<% end %>

src/app/views/users/show.html.erb
 <div class = "card m-3" style="width: 18rem;">
    <div class="card-img-top">
      <p><%= image_tag @user.get_profile_image(100,100) %></p>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @user.name %></h5>
      <%= link_to "Profile Edit", edit_user_path(@user.id), class: "btn btn-primary" %>
    </div>
  </div>

<div class="card-list-container py-5">
  <% @post_books.each do |post_book| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <div class="row">
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_book_path(post_book.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_book.title %></span></strong>
            <% end %>
          </p>
          <p class="card-text">Story：<%= post_book.body %></p>
          <span><i class="fas fa-user"></i> By <%= post_book.user.name %> ｜ </span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>